version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_username
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/songs
      MONGODB_USERNAME: mongo_username
      MONGODB_PASSWORD: mongo_password
    depends_on:
      - mongo
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - api
  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80